# Generated by Django 5.2 on 2025-05-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='documento',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
