# Generated by Django 5.2 on 2025-05-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='baja', max_length=10)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en progreso', 'En Progreso'), ('completada', 'Completada')], default='pendiente', max_length=15)),
                ('category', models.CharField(choices=[('urgente e importante', 'Urgente e Importante'), ('urgente y no importante', 'Urgente y No Importante'), ('no urgente, pero importante', 'No Urgente, pero Importante'), ('no urgente y no importante', 'No Urgente y No Importante')], default='no urgente y no importante', max_length=30)),
            ],
        ),
    ]
